# Generated by Django 4.0 on 2024-05-17 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='expiry',
            new_name='expire',
        ),
    ]
